version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extractor_api
    expose:
      - "8000"
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"  # <-- Añadimos HTTPS
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # <-- Montamos los certificados
    depends_on:
      - api
    restart: always
