version: "3.9"
services:
  extractor_api:
    build: .
    container_name: extractor_api
    ports:
      - "8000:8000"
    expose:
      - "8000"
  
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - extractor_api
